# Based on:
#   Publishing Docker images - GitHub Docs
#     https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
#   Distribute build across multiple runners § Multi-platform image with GitHub Actions | Docker Docs
#     https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

name: Build and publish

on:
  release:
    types: [published]
  push:
    branches: [mian, dev]  # always make changes on dev and make PR to mian

env:
  REGISTRY_IMAGE: ChocoLZS/streamlink-eplus_jp-object_storage
  TAG_NAME: ${{ github.event_name == 'push' && (github.ref_name == 'mian' && 'latest' || 'unstable') || '' }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
    permissions:
      packages: write
    # https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
    concurrency:
      group: std::lock_guard
    timeout-minutes: 20
    steps:
      -
        name: Prepare platform info
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV  
      -
        name: Check out the repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Tag or Branch Type
        id: tag_or_branch_check
        run: |
          BRANCH_NAME=$(echo "$CURRENT_BRANCH_NAME" | sed 's|/|_|g')
          if [[ ${BRANCH_NAME} == main ]]; then
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          elif [[ ${BRANCH_NAME} == dev ]]; then
            echo "TAG_NAME=canary" >> $GITHUB_ENV
          else
            echo "TAG_NAME=canary-${BRANCH_NAME}" >> $GITHUB_ENV
          fi
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          file: app/tweet-forwarder/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.push.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      -
        name: Upload digest
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b  # v4.3.4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
